### ISSUE TITLE
How to configure missing

### ISSUE THREAD

**Issue by iadegesso** [caugner/ep_footer#1]
Hi,
could you provide a more extensive description of the piece of JSON that will be added to the setting.json file?

Thanks a lot

Iade Gesso, MSc, PhD

**Comment by caugner** [comment]
Hi Iade,

there you go:

``` json
{
  "ip": "0.0.0.0",
  "port" : 9001,

   "dbType" : "mysql",
   "dbSettings" : { ... },

   "ep_footer" : "This will be appended to the HTML content (inside the body)",

   "loglevel": "INFO"
}
```

I have been using this to add Piwik analytics to my EtherPad.

Claas
